import mongoose from 'mongoose';

const CategorySchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  title: { type: String, required: true },
  slug: { type: String },
  subtitle: { type: String, default: '' },
  description: { type: String, default: '' },
  longDescription: { type: String, default: '' },
  image: { type: String, required: true },
  bannerImage: { type: String },
  color: { type: String, required: true },
  accentColor: { type: String },
  buttonColor: { type: String },
  products: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Product' }],
  mobileTitle: { type: String },
  mobileShortDesc: { type: String },
  mobileActiveDesc: { type: String },
  mobileHeroImage: { type: String },
  mobileImgPosition: { type: String, default: 'center' },
  desktopImgPosition: { type: String, default: 'center' },
  desktopFeaturedProductId: { type: String },
  watermarkText: { type: String },
  watermarkOpacity: { type: Number, default: 0.04 },
  ctaText: { type: String },
  ctaLink: { type: String },
  enabled: { type: Boolean, default: true },
  featured: { type: Boolean, default: false },
  order: { type: Number, default: 0 },
  isDefault: { type: Boolean, default: false },
  seoTitle: { type: String },
  seoDescription: { type: String },
  lowStockThreshold: { type: Number, default: 10 },
}, { timestamps: true });

export default mongoose.models.Category || mongoose.model('Category', CategorySchema);
